### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by ItEndsWithTens**
- Make GraphicsDeviceOptions project-specific
- Break most classes out into dedicated files
- Consolidate Gtk library directories
- Simplifiy backend initialization
- Check for valid GraphicsDevice before updating viewport

There's been a decent amount of change, and I thought it only polite to bring this new code in myself; if instead you'd like to pick through the changes one by one, feel free to just close this PR and do the merge by hand.

Now that I've eliminated the ControlReady boolean, I switched to checking for a null GraphicsDevice in pUpdateViewport, which does the job for the time being, namely in WPF. If it becomes necessary to add something to VeldridSurface to track the state of whether or not a backend is initialized, I can do that, but it seemed worthwhile to try and avoid unnecessary extra properties, so I just did this for now.

Also of note is the reorganization of bin and obj output into a top level "artifacts" directory. This not only allowed combining the Gtk projects into one directory (problems arose with restore and build otherwise), but also more closely matches the Eto and Eto.OpenTK project structure. It's also a little more convenient to get to build results without drilling down quite as far.

Keep in mind that as a result of said reorganization you may need to delete any old bin and obj directories yourself to avoid, for example, duplicate assembly attribute errors.

I have more changes in mind, but I didn't want to let things deviate too drastically before merging the code with your fork.

### CODE REVIEW

**Comment by ItEndsWithTens** [comment]
Hope it's not too bothersome, but since this was still open I pushed an extra commit to it that cleans up OpenGL context creation. Keeps all the GL version and context flags stuff in one place, instead of having to change it across multiple handlers. Works on all the platforms we support so far, in my experience.

**Comment by philstopford** [comment]
Sorry - not ignoring this; just wrangling some things at the moment. I'll get to it eventually.

**Comment by philstopford** [comment]
Thanks. Curiously, in my bigger applications, this change brought a complaint that there was no depth buffer for this line in Draw() in VeldridDriver.cs : 

CommandList.ClearDepthStencil(1.0f);

I'm not sure why yet. The test application didn't object.

**Comment by ItEndsWithTens** [comment]
Oh, sorry, I neglected to expressly call that out: the GraphicsDeviceOptions is now an application-specific thing, and you'll need to pass in your own when creating a VeldridSurface. I updated your test application as part of my changes, [as seen here](https://github.com/philstopford/Eto.Veldrid/blob/beaddb1856c53dc7800405f0e7142bb0802cae2b/test/TestEtoVeldrid/MainForm.cs#L58), but forgot to mention it. There's a default, which just uses the defaults for the GraphicsDeviceOptions class, but that doesn't have a depth buffer, so I suspect that's the source of your problem.

**Comment by philstopford** [comment]
Got it. Thanks again.

Unrelated, but do you have a thought for how it might be possible to perform an on-the-fly update during drag (where the system tries to draw what it can during the drag event at each interval)?

**Comment by ItEndsWithTens** [comment]
I can't think of anything off the top of my head except what you've got already in VeldridDriver, with the "dragging" bool; i.e. tie a handler to the VeldridSurface's MouseMove event and check whether the user's dragging, then if so update the viewport.

**Pull request merged**
