### PR TITLE
Eliminate use of Eto.Gl/Eto.OpenTK

### PR DESCRIPTION
**Pull request by ItEndsWithTens**
Hey! So. After my last pull request I realized I hadn't properly tested the MouseWheel event, and upon doing so it wasn't being bubbled correctly. Of course. I mulled over my options for a bit, but ultimately figured it was too much effort to keep digging in my previous direction with the RenderTarget and/or GLSurface buried inside my custom control, itself based on a Panel that wasn't really the right base control anyway... Sunk Costs, and all that. So I did what I'd been putting off for a while now, and tried stripping the Eto.Gl/Eto.OpenTK dependency completely out of the equation, hoping less indirection would simplify the project enough to let me see where to go next.

I still had to duplicate select bits of Eto.OpenTK code to get OpenGL running properly, but in the end everything **worked**. I'm still reeling from having a Eureka moment that went somewhere. The situation's actually even better than I expected:
- KeyDown, KeyUp, MouseDown, MouseUp, and MouseWheel all now work as expected.
- Rendering no longer requires an instance of GLSurface, or a decent number of its features and accumulated cruft, as Veldrid only needs a handful of them. That's not to say it won't need to be massaged for various edge cases, but it works well enough for starters.
- Resize performance is through the roof, and a few simple Draw calls in response to the right events on various platforms have all but eliminated flicker, as far as I've seen.

Your test code doesn't work in WinForms, but I believe that's as it was before my changes; something to do with VeldridDriver.Draw and when it's getting called, I think. The WPF project runs fine for me, though, WASD navigation (after clicking to focus), click dragging, and mousewheel zoom.

If you want to see everything else I mentioned in action across Eto platforms, and Veldrid backends, you can always try out [the ItEndsWithTens/Eto.Veldrid master branch](https://github.com/ItEndsWithTens/Eto.Veldrid/tree/master), which has my multi-colored test rectangle project. Click to stop/start the rotation, tap the C key (after clicking to give the control focus) to change direction, and scroll the mouse wheel to speed up or slow down. I'll update my readme with those instructions eventually, I swear.

I promise I tried not to get carried away, but I had a bolt of inspiration hit me last night and I couldn't resist. This, I think, is the real avenue to pursue, and should lend itself more easily to future cleanup and hardening.

This should be my last big pull request for the immediate future, I hope it works better for you than the last one!

### CODE REVIEW

**Comment by philstopford** [comment]
Looks awesome. I'll be restarting my efforts here, to get the viewport to fill the window, etc. Thanks again for your efforts!

**Comment by philstopford** [comment]
OK. So on my intel-only laptop, the viewport fits the window fully. On my high DPI system (nVidia 1060), the viewport doesn't fill the screen

image

**Comment by ItEndsWithTens** [comment]
Ah, dang it, so close! I can't say off hand what causes that. If I can find some way to test high DPI I'll take a look, but my current system doesn't support it, as far as I know. I'll see if I can find some workaround for testing purposes.

**Comment by philstopford** [comment]
That image was with 125% text zoom. Setting to 100%, the window frame is filled.

**Comment by ItEndsWithTens** [comment]
Ah, thanks! The text zoom alone doesn't cause problems on my system, but when I set the "make everything bigger" slider to 125% I get the behavior you're seeing. I'll see if I can track down the issue now.

**Comment by ItEndsWithTens** [comment]
Okay, based on [what I've read](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/layout-considerations-for-the-windowsformshost-element), it looks like the problem stems from the difference in how controls are measured in WPF and WinForms. The former uses device-independent pixels, while the latter uses physical, hardware pixels. We're mixing the two by way of WindowsFormsHost.

As an example, if you had a 100 pixel wide control in WinForms, and DPI changes meant it needed to be scaled by a factor of 2, it would be displayed as 200 pixels wide, and have a width of 200.

In WPF, by contrast, a 100 pixel wide control scaled by a factor of 2 would be displayed as 200 pixels wide, but still be considered to have a width of 100. Or so I believe based on the results I'm getting.

You can see this by setting a breakpoint somewhere that lets you access the insides of WpfVeldridSurfaceHandler, and examining the difference between Control.Width and WinFormsControl.Width, just as an example. The WinForms control is adjusted properly based on the DPI: our 400x350 control at 125% scale becomes 500x438, but the WPF control underlying the WpfVeldridSurfaceHandler is still shown as being 400x350. When your code draws the grid, it quite reasonably assumes that the VeldridSurface's width and height are accurate, when in fact they need to be tweaked to accommodate this WPF/WinForms/DPI business.

The question then is what to do about it. I'm experimenting now, and I'll get back to you when I have something that works.

**Pull request merged**
